// Sprout Resources — the template library users browse and pick from.
// A full spread of the formats homeschooling parents actually use for ages
// 3-12, grouped under six top-level topics.

import type { BlockKind, WorksheetTemplate } from "./types";

export const TEMPLATES: WorksheetTemplate[] = [
  // ── Math ───────────────────────────────────────────────────────────────
  {
    id: "addition",
    title: "Addition",
    blurb: "Practice problems with room to work them out.",
    emoji: "➕",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-emerald-100 text-emerald-700",
    plan: ["instructions", "math", "column-math"],
    brief: "Addition facts sized to the age: a full set of horizontal problems plus stacked column sums.",
  },
  {
    id: "subtraction",
    title: "Subtraction",
    blurb: "Take-away practice with answer boxes.",
    emoji: "➖",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-emerald-100 text-emerald-700",
    plan: ["instructions", "math", "column-math"],
    brief: "Subtraction facts sized to the age: horizontal problems plus stacked column problems.",
  },
  {
    id: "multiplication",
    title: "Multiplication",
    blurb: "Times-table practice plus word problems.",
    emoji: "✖️",
    ageMin: 7,
    ageMax: 12,
    accent: "bg-teal-100 text-teal-700",
    plan: ["instructions", "math", "short-answer"],
    brief: "Multiplication facts to the right level, then several word problems to solve.",
  },
  {
    id: "division",
    title: "Division",
    blurb: "Sharing and grouping with answer boxes.",
    emoji: "➗",
    ageMin: 8,
    ageMax: 12,
    accent: "bg-teal-100 text-teal-700",
    plan: ["instructions", "math", "short-answer"],
    brief: "Division facts sized to the age, then a couple of sharing word problems.",
  },
  {
    id: "fractions",
    title: "Fractions",
    blurb: "Shade, name, and compare fractions.",
    emoji: "🍕",
    ageMin: 7,
    ageMax: 12,
    accent: "bg-orange-100 text-orange-700",
    plan: ["instructions", "fill-blank", "short-answer"],
    brief: "Identify, shade and compare simple fractions; finish with fraction-of-a-number problems.",
  },
  {
    id: "place-value",
    title: "Place Value",
    blurb: "Tens, ones, hundreds, and ordering numbers.",
    emoji: "🔢",
    ageMin: 6,
    ageMax: 10,
    accent: "bg-amber-100 text-amber-700",
    plan: ["instructions", "missing-numbers", "short-answer"],
    brief: "Place value: name the value of a digit, expanded form, ordering numbers.",
  },
  {
    id: "telling-time",
    title: "Telling Time",
    blurb: "Read and write times to the hour and half hour.",
    emoji: "🕐",
    ageMin: 6,
    ageMax: 10,
    accent: "bg-sky-100 text-sky-700",
    plan: ["instructions", "short-answer", "matching"],
    brief: "Telling time: write the time shown, match clocks to times, elapsed-time questions for older kids.",
  },
  {
    id: "money",
    title: "Money Math",
    blurb: "Add up dollars and cents and make change.",
    emoji: "💰",
    ageMin: 6,
    ageMax: 11,
    accent: "bg-lime-100 text-lime-700",
    plan: ["instructions", "math", "short-answer"],
    brief: "Money with $ and ¢: totalling amounts and making change, plus short word problems.",
  },
  {
    id: "missing-numbers",
    title: "Missing Numbers",
    blurb: "Fill the gaps in the sequence.",
    emoji: "🔟",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-amber-100 text-amber-700",
    plan: ["instructions", "missing-numbers"],
    brief: "Number sequences (counting on, skip counting) with several blanks to fill.",
  },
  {
    id: "word-problems",
    title: "Word Problems",
    blurb: "Real-life math with space to show your work.",
    emoji: "🧠",
    ageMin: 6,
    ageMax: 12,
    accent: "bg-teal-100 text-teal-700",
    plan: ["instructions", "short-answer"],
    brief: "Several one- and two-step word problems sized to the age, with room to work and answer.",
  },
  {
    id: "shapes",
    title: "Shapes & Geometry",
    blurb: "Name shapes, count sides, and draw them.",
    emoji: "🔷",
    ageMin: 3,
    ageMax: 8,
    accent: "bg-indigo-100 text-indigo-700",
    plan: ["instructions", "matching", "draw"],
    brief: "Recognise and name 2D shapes, match shapes to names, draw and count sides.",
  },

  // ── Counting ────────────────────────────────────────────────────────────
  {
    id: "counting",
    title: "Counting & Numbers",
    blurb: "Count the objects and write how many.",
    emoji: "🧮",
    ageMin: 3,
    ageMax: 7,
    accent: "bg-amber-100 text-amber-700",
    plan: ["instructions", "count", "missing-numbers"],
    brief: "Count sets of objects and write the total, then fill the gaps in a number line.",
  },
  {
    id: "skip-counting",
    title: "Skip Counting",
    blurb: "Count by 2s, 5s, and 10s.",
    emoji: "⏭️",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-amber-100 text-amber-700",
    plan: ["instructions", "missing-numbers"],
    brief: "Skip-count sequences by 2s, 5s, 10s (and 3s for older) with blanks to fill.",
  },
  {
    id: "patterns",
    title: "Patterns",
    blurb: "Spot the pattern and what comes next.",
    emoji: "🔁",
    ageMin: 3,
    ageMax: 7,
    accent: "bg-violet-100 text-violet-700",
    plan: ["instructions", "missing-numbers", "draw"],
    brief: "Complete repeating patterns (shapes, colors, numbers) and draw what comes next.",
  },
  {
    id: "matching",
    title: "Matching",
    blurb: "Draw a line to connect the pairs.",
    emoji: "🧩",
    ageMin: 3,
    ageMax: 8,
    accent: "bg-violet-100 text-violet-700",
    plan: ["instructions", "matching"],
    brief: "Match items across two columns (numeral to word, picture to label, opposites).",
  },

  // ── Reading ─────────────────────────────────────────────────────────────
  {
    id: "reading",
    title: "Reading Comprehension",
    blurb: "Read the passage, then answer the questions.",
    emoji: "📚",
    ageMin: 6,
    ageMax: 12,
    accent: "bg-indigo-100 text-indigo-700",
    plan: ["passage", "short-answer", "multiple-choice"],
    brief: "An age-appropriate passage, then comprehension questions (main idea, detail, why) and one multiple choice.",
  },
  {
    id: "phonics",
    title: "Phonics & Sounds",
    blurb: "Beginning sounds and simple CVC words.",
    emoji: "🔊",
    ageMin: 4,
    ageMax: 7,
    accent: "bg-pink-100 text-pink-700",
    plan: ["instructions", "trace", "fill-blank"],
    brief: "Beginning sounds and CVC words: trace the sounds, then fill the missing letter in words.",
  },
  {
    id: "sight-words",
    title: "Sight Words",
    blurb: "Trace, write, and use this week's words.",
    emoji: "👀",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-pink-100 text-pink-700",
    plan: ["instructions", "trace", "fill-blank"],
    brief: "Common sight words for the age: trace each, then use it in a fill-in-the-blank sentence.",
  },
  {
    id: "rhyming",
    title: "Rhyming Words",
    blurb: "Match and finish the rhymes.",
    emoji: "🎵",
    ageMin: 4,
    ageMax: 8,
    accent: "bg-pink-100 text-pink-700",
    plan: ["instructions", "matching", "fill-blank"],
    brief: "Match pairs of rhyming words, then finish sentences with a word that rhymes.",
  },

  // ── Writing ─────────────────────────────────────────────────────────────
  {
    id: "spelling",
    title: "Spelling",
    blurb: "Practise this week's spelling list.",
    emoji: "✏️",
    ageMin: 5,
    ageMax: 10,
    accent: "bg-rose-100 text-rose-700",
    plan: ["instructions", "trace", "fill-blank"],
    brief: "A set of age-appropriate spelling words: trace them, then use each in a sentence.",
  },
  {
    id: "fill-blank-story",
    title: "Fill-in-the-Blank Story",
    blurb: "Complete the story using the word bank.",
    emoji: "📖",
    ageMin: 6,
    ageMax: 12,
    accent: "bg-orange-100 text-orange-700",
    plan: ["instructions", "word-bank", "fill-blank"],
    brief: "A short themed story with blanks plus a word bank to choose from.",
  },
  {
    id: "creative-writing",
    title: "Creative Writing",
    blurb: "A fun prompt and lines to write a story.",
    emoji: "💭",
    ageMin: 6,
    ageMax: 12,
    accent: "bg-rose-100 text-rose-700",
    plan: ["instructions", "handwriting"],
    brief: "A vivid age-appropriate writing prompt, sentence starters, and plenty of lines to write on.",
  },
  {
    id: "grammar",
    title: "Grammar",
    blurb: "Nouns, verbs, capitals, and punctuation.",
    emoji: "🔤",
    ageMin: 6,
    ageMax: 12,
    accent: "bg-rose-100 text-rose-700",
    plan: ["instructions", "fill-blank", "short-answer"],
    brief: "Parts of speech and punctuation: identify nouns/verbs, fix capitals and end marks, rewrite sentences.",
  },
  {
    id: "sentence-building",
    title: "Sentence Building",
    blurb: "Turn words into full sentences.",
    emoji: "🧱",
    ageMin: 5,
    ageMax: 9,
    accent: "bg-rose-100 text-rose-700",
    plan: ["instructions", "word-bank", "handwriting"],
    brief: "Build and write complete sentences from a word bank, mind capitals and full stops.",
  },

  // ── Tracing ─────────────────────────────────────────────────────────────
  {
    id: "letter-tracing",
    title: "Letter Tracing",
    blurb: "Trace the letters, then write them.",
    emoji: "🅰️",
    ageMin: 3,
    ageMax: 6,
    accent: "bg-sky-100 text-sky-700",
    plan: ["instructions", "trace", "handwriting"],
    brief: "Letter formation: trace rows of letters, then a row to write independently.",
  },
  {
    id: "number-tracing",
    title: "Number Tracing",
    blurb: "Trace numbers and practise writing them.",
    emoji: "1️⃣",
    ageMin: 3,
    ageMax: 6,
    accent: "bg-sky-100 text-sky-700",
    plan: ["instructions", "trace", "handwriting"],
    brief: "Number formation: trace numerals (bigger numbers for older kids), then write them.",
  },
  {
    id: "line-tracing",
    title: "Line Tracing",
    blurb: "Pre-writing lines and curves.",
    emoji: "〰️",
    ageMin: 3,
    ageMax: 5,
    accent: "bg-sky-100 text-sky-700",
    plan: ["instructions", "trace", "draw"],
    brief: "Pre-writing strokes: trace straight, curved and zig-zag lines, then copy them.",
  },

  // ── Creativity ──────────────────────────────────────────────────────────
  {
    id: "draw-label",
    title: "Draw & Label",
    blurb: "Draw it, then label the parts.",
    emoji: "🎨",
    ageMin: 4,
    ageMax: 10,
    accent: "bg-fuchsia-100 text-fuchsia-700",
    plan: ["instructions", "draw", "handwriting"],
    brief: "A draw-and-label activity (a plant, an animal, a scene) with lines to label or write a sentence.",
  },
  {
    id: "color-by-number",
    title: "Color by Number",
    blurb: "Solve, then color by the answer.",
    emoji: "🖍️",
    ageMin: 4,
    ageMax: 9,
    accent: "bg-fuchsia-100 text-fuchsia-700",
    plan: ["instructions", "math", "draw"],
    brief: "Simple problems whose answers map to colors, plus a picture area to color in.",
  },
  {
    id: "life-cycle",
    title: "Life Cycle & Science",
    blurb: "Draw and label how something grows.",
    emoji: "🦋",
    ageMin: 5,
    ageMax: 10,
    accent: "bg-fuchsia-100 text-fuchsia-700",
    plan: ["instructions", "draw", "short-answer"],
    brief: "Draw and label a life cycle or simple science topic, then answer a few questions about it.",
  },
];

// The freeform "Build your own" path. A pseudo-template, deliberately NOT in
// TEMPLATES (so it never shows as a library card). getTemplate serves it so
// /resources/custom reuses the exact builder — same chat, render, edit presets,
// save. Only the entry point differs. Generation reuses the Venice pipeline in
// a freeform branch; sheets made this way are the only ones publishable.
export const CUSTOM_TEMPLATE: WorksheetTemplate = {
  id: "custom",
  title: "Build Your Own",
  blurb: "Describe any worksheet and Sprout builds it from scratch.",
  emoji: "✨",
  ageMin: 3,
  ageMax: 13,
  accent: "bg-lime-100 text-lime-700",
  plan: ["instructions", "short-answer"],
  brief: "Whatever the parent describes, built as a real printable worksheet.",
};

export function getTemplate(id: string): WorksheetTemplate | undefined {
  if (id === CUSTOM_TEMPLATE.id) return CUSTOM_TEMPLATE;
  return TEMPLATES.find((t) => t.id === id);
}

export function ageBand(t: WorksheetTemplate): string {
  return `Ages ${t.ageMin}-${t.ageMax}`;
}

export const BLOCK_KINDS: BlockKind[] = [
  "instructions",
  "trace",
  "handwriting",
  "fill-blank",
  "word-bank",
  "math",
  "column-math",
  "count",
  "matching",
  "multiple-choice",
  "short-answer",
  "missing-numbers",
  "passage",
  "draw",
];

// The six top-level topics shown in the library for browse + search.
export const TOPICS: { key: string; label: string; emoji: string }[] = [
  { key: "math", label: "Math", emoji: "🔢" },
  { key: "counting", label: "Counting", emoji: "🧮" },
  { key: "reading", label: "Reading", emoji: "📚" },
  { key: "writing", label: "Writing", emoji: "✏️" },
  { key: "tracing", label: "Tracing", emoji: "🅰️" },
  { key: "creativity", label: "Creativity", emoji: "🎨" },
];

const TOPIC_MAP: Record<string, string> = {
  addition: "math",
  subtraction: "math",
  multiplication: "math",
  division: "math",
  fractions: "math",
  "place-value": "math",
  "telling-time": "math",
  money: "math",
  "missing-numbers": "math",
  "word-problems": "math",
  shapes: "math",
  counting: "counting",
  "skip-counting": "counting",
  patterns: "counting",
  matching: "counting",
  reading: "reading",
  phonics: "reading",
  "sight-words": "reading",
  rhyming: "reading",
  spelling: "writing",
  "fill-blank-story": "writing",
  "creative-writing": "writing",
  grammar: "writing",
  "sentence-building": "writing",
  "letter-tracing": "tracing",
  "number-tracing": "tracing",
  "line-tracing": "tracing",
  "draw-label": "creativity",
  "color-by-number": "creativity",
  "life-cycle": "creativity",
};

export function topicForTemplate(id: string): string {
  return TOPIC_MAP[id] ?? "math";
}
