import type { Metadata } from "next";
import { ArrowLeft, Ban, Check, Cpu, ExternalLink, Laptop, Lock } from "lucide-react";
import { GlassLink } from "@/components/ui/glass";

export const metadata: Metadata = {
  title: "Your data is yours · Sprout Resources",
  description: "Exactly how Sprout Resources handles your data: the Venice model we run, what is never stored, and proof from the source.",
};

const lightCard =
  "rounded-2xl bg-[#FBF7EE] border border-[#2E5A35]/15 shadow-[0_16px_36px_-12px_rgba(0,0,0,0.7),inset_0_1px_0_rgba(255,255,255,0.7)]";

const POINTS = [
  {
    icon: Cpu,
    title: "The model we run",
    body: "Every worksheet is generated by Venice AI, running the open Qwen3-235B model. Its exact id is qwen3-235b-a22b-instruct-2507.",
  },
  {
    icon: Lock,
    title: "What you type is not stored",
    body: "Your request is sent to Venice to build the worksheet, then relayed without being stored. Venice does not store or log the prompt or the response on its servers.",
  },
  {
    icon: Ban,
    title: "Nothing is kept or trained on",
    body: "Because nothing is stored, there is nothing for anyone to sell, and nothing to train an AI model on. Not your words, not your child's name.",
  },
  {
    icon: Laptop,
    title: "We don't keep it either",
    body: "Your worksheets and your kids' profiles are saved in your own browser, on your device, not on a Sprout server.",
  },
  {
    icon: Check,
    title: "You own all of it",
    body: "Everything you make here is yours.",
  },
];

export default function ResourcesPrivacy() {
  return (
    <div className="mx-auto max-w-2xl">
      <GlassLink href="/resources" className="mb-6 h-9 gap-1 px-3 text-sm">
        <ArrowLeft className="size-4" /> Library
      </GlassLink>

      <h1 className="text-sprout-cream text-3xl font-bold tracking-[-0.02em]">Your data is yours</h1>
      <p className="text-sprout-cream/70 mt-2 max-w-xl">
        You make the worksheets. You keep them. No tech giant gets a copy, no data broker gets a row in a spreadsheet, no model gets trained on your kid. This is what taking it back looks like. Here is exactly how it works, so you can check it for yourself.
      </p>

      <div className={`${lightCard} mt-6 divide-y divide-[#2E5A35]/10`}>
        {POINTS.map(({ icon: Icon, title, body }) => (
          <div key={title} className="flex gap-4 p-5">
            <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#2E5A35]/10 text-[#2E5A35]">
              <Icon className="size-5" />
            </span>
            <div>
              <h2 className="font-bold text-[#1B3722]">{title}</h2>
              <p className="mt-1 text-[15px] leading-relaxed text-[#1B3722]/70">{body}</p>
            </div>
          </div>
        ))}
      </div>

      <div className={`${lightCard} mt-5 p-5`}>
        <p className="text-[15px] leading-relaxed text-[#1B3722]/80">
          Don't take our word for it. Venice spells out the same thing in their own privacy policy, including that your prompts pass through without being stored and your history stays on your device.
        </p>
        <GlassLink href="https://venice.ai/privacy" target="_blank" rel="noopener noreferrer" className="mt-4 h-10 px-4 text-sm text-[#1B3722]">
          Read Venice's privacy policy <ExternalLink className="size-4" />
        </GlassLink>
      </div>

      <div className={`${lightCard} mt-5 p-5`}>
        <p className="text-[15px] leading-relaxed text-[#1B3722]/80">
          Most of the internet is built the other way around. You are the product, your kids are the training data, and your week gets sold to whoever pays. Sprout is the corner that does not work like that. You are one of the parents taking it back and growing the next generation on your own terms. That is the whole reason we built this.
        </p>
      </div>

      <p className="text-sprout-cream/45 mt-6 text-xs">
        This page describes how Sprout Resources generates worksheets. Venice's guarantees are Venice's own; we link to their policy as the source of truth.
      </p>
    </div>
  );
}
